### ISSUE TITLE
(bug) Dark mode broken on Linux

### ISSUE THREAD

**Issue by kra-mo** [relagit/relagit#27] opened 2024-05-17 15:38 UTC
### What happened?

When switching to dark theme on Linux, parts of the app remain white/gray until a relaunch. The menu bar remains white even after that.

[Screencast from 2024-05-17 17-34-32.webm](https://github.com/relagit/relagit/assets/93832451/01f5fc30-faf2-4809-9eb7-36749efb76c7)

### Version

0.15.0

### What systems are you seeing the problem on?

Linux

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment] 2024-05-18 07:31
Hey there, can you please see if the issue is resolved with the [latest commit](https://github.com/relagit/relagit/commit/59bd99a96b9d2eee4ceccdc3838f0e2bdedaf8f3)

**Comment by kra-mo** [comment] 2024-05-18 07:55
> Hey there, can you please see if the issue is resolved with the [latest commit](https://github.com/relagit/relagit/commit/59bd99a96b9d2eee4ceccdc3838f0e2bdedaf8f3)

Building seems to fail, not exactly sure why:

```
x Build failed in 35ms
error during build:
Error: [transform-file] [vite-plugin-replace]: The replacement option 'to' is not of type 'string' or 'Function'
file: /var/home/kramo/Projects/RelaGit/packages/main/src/index.ts
    at /var/home/kramo/Projects/RelaGit/node_modules/vite-plugin-replace/index.js:21:23
    at Array.forEach (<anonymous>)
    at execSrcReplacements (/var/home/kramo/Projects/RelaGit/node_modules/vite-plugin-replace/index.js:14:22)
    at Object.transform (/var/home/kramo/Projects/RelaGit/node_modules/vite-plugin-replace/index.js:45:27)
    at Object.handler (file:///var/home/kramo/Projects/RelaGit/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67712:19)
    at file:///var/home/kramo/Projects/RelaGit/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19778:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by kra-mo** [comment] 2024-05-18 08:27
@TheCommieAxolotl 

Okay, hard-coding the environment variables to empty strings fixes the build, but the commit does not fix either of the issues, no

**Comment by TheCommieAxolotl** [comment] 2024-05-18 08:31
Can you please send your Debug Info as well as a screenshot of the appearance tab in settings? 

<img width="321" alt="SCR-20240518-qeep" src="https://github.com/relagit/relagit/assets/87679354/2a643e9c-8835-41ad-8995-0eeec9db67c2">

**Comment by kra-mo** [comment] 2024-05-18 08:33
Debug info:
```
{"platform":"linux","version":"0.15.0","commit":"59bd99a","location":{"history":false,"selected":"<Repository>","isRefetching":false,"imageDisplay":"sidebyside","dragState":null,"palette":false,"commit":"<None>","commitFile":"<None>","file":"<None>"},"layers":"modal, notification","modals":"Active: settings, Previous: undefined"}
```

The Appearance tab:

![Screenshot from 2024-05-18 10-32-18](https://github.com/relagit/relagit/assets/93832451/734ef4ad-12b8-4a62-a738-5fcfcef93b39)

**Comment by kra-mo** [comment] 2024-05-18 08:34
The same thing happens when switching to light mode if the app was initially launched in dark mode, by the way.

The menu bar issue seems to be unrelated.

**Comment by kra-mo** [comment] 2024-05-18 08:37
Aaaaand the assets seem to not switch over correctly either, but probably another unrelated issue:

[Screencast from 2024-05-18 10-36-56.webm](https://github.com/relagit/relagit/assets/93832451/5778d4fa-8751-4e84-b335-f62988575743)

**Comment by TheCommieAxolotl** [comment] 2024-05-18 08:50
Ah i see the issue here, the problem is that on first startup the app tries to enable vibrancy.

For the meantime, you can edit `~/.relagit/settings.json` and set `"vibrancy": false`

**Comment by TheCommieAxolotl** [comment] 2024-05-18 08:52
Fixed in [3b2103](https://github.com/relagit/relagit/commit/3b210360958d84927d7f9f57b667876698f50e7c)

**Comment by kra-mo** [comment] 2024-05-18 08:53
> For the meantime, you can edit ~/.relagit/settings.json and set "vibrancy": false

That does fix it, yeah.

But the issue with the menu bar and the assets are still there. Should I open separate issues for those?

**Closed by TheCommieAxolotl** 2024-05-18 08:52 UTC
Labels: bug, triage

**Comment by TheCommieAxolotl** [comment] 2024-05-18 09:10
If I implement your other issue about the client-side window decorations then that will be fixed, for the assets I'll take a look at it tonight/tomorrow (I knew about that before this)

**Comment by kra-mo** [comment] 2024-05-18 09:10
Alright ^^
