### ISSUE TITLE
(bug) Doesn't run on windows 11

### ISSUE THREAD

**Issue by Diego-Barrera-07** [relagit/relagit#49] opened 2024-12-17 05:04 UTC
### What happened?

I just encountered this problem when trying to run the application it doesn't run, it doesn't show me any error output, it just thinks for a few seconds and nothing happens. I've already installed and uninstalled the application 3 times, but the error persists.

Edition: Windows 11 Pro
Version: 23H2
OS Version: 22631.4602

### Version

0.16.8

### What systems are you seeing the problem on?

Windows

### Relevant log output

```shell
It doesn't show any output.
```

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by je-sendra** [comment] 2024-12-18 08:01
I've just installed Relagit and had the same problem on the first run. Since there was no error message in the Event Logs, I've decided to try to run RelaGit from a terminal to see what was happening.

I got the following output:

```powershell
PS C:\Program Files\RelaGit> .\RelaGit.exe
PS C:\Program Files\RelaGit>
[RelaGit] Startup (production)
[RelaGit] Version: 0.16.8
[RelaGit] Running on: win32 x64
[RelaGit] Commit: 35dc216
[24876:1218/085733.831:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acceso denegado. (0x5)
[24876:1218/085733.833:ERROR:disk_cache.cc(208)] Unable to create cache
[24876:1218/085733.831:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acceso denegado. (0x5)
[24876:1218/085733.833:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[24876:1218/085733.833:ERROR:disk_cache.cc(208)] Unable to create cache
[24876:1218/085733.834:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[77172:1218/085733.929:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acceso denegado. (0x5)
[77172:1218/085733.931:ERROR:disk_cache.cc(208)] Unable to create cache
```

The same error happens if executing with administrator rights.

**Comment by je-sendra** [comment] 2024-12-18 08:19
I've just seem this is a a dupe of #23

There are some solutions to try in that thread

**Comment by Diego-Barrera-07** [comment] 2024-12-19 20:59
Thanks, you are right @je-sendra  that the thread is duplicated, however I did not find a solution in the previous one. I will continue trying to be able to use the tool. You can close the thread @TheCommieAxolotl  or if you have a new solution I would be happy to use it.

**Comment by TheCommieAxolotl** [comment] 2024-12-19 23:58
I still unfortunately have no way to diagnose or fix this issue, as far as i can tell it seems to be an underlying electron issue with something i am doing in the `ipc.ts` file, but i've had no luck.

**Closed by TheCommieAxolotl** 2024-12-19 23:58 UTC
Labels: bug, triage

**Comment by je-sendra** [comment] 2024-12-22 12:23
@TheCommieAxolotl I might be able to help somewhere these winter holidays, I really want to drop GitHub Desktop, but everyone who needs to use Windows is currently just locked out of the app :(

**Comment by respberryx** [comment] 2025-01-05 13:39
I will just add from myself that I think I fixed the error, I will clean up the code and make a PR but I need to test more. Weirdly enough after my changes running RelaGit opens Cursor???
