### ISSUE TITLE
(bug) Error after resizing window in Ubuntu

### ISSUE THREAD

**Issue by iglnierod** [relagit/relagit#18] opened 2024-04-26 21:03 UTC
### What happened?

Hi! I just installed the app and I'm getting this error when resizing the app window.
It just happens when the app is maximized (not F11).I make it smaller by double clicking the app title bar and this error comes up,
here you have a screenshot:
![image](https://github.com/relagit/relagit/assets/115586378/b73726fa-7775-42e9-88f9-0b339be3d54d)

App keeps working just fine after closing the dialog but wanted you to know about this.

### Version

0.14.8

### What systems are you seeing the problem on?

Linux

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment] 2024-04-26 23:00
Thanks, I've known about this bug for a while, it seems to be caused by quick successive settings updates which result in a JSON file with two trailing `}}`, I'll have another look today at removing the issue!

**Comment by TheCommieAxolotl** [comment] 2024-04-27 02:08
@iglnierod If possible, can you try with the latest commit ([8d0c531](https://github.com/relagit/relagit/commit/8d0c53192a368a9b3ab697a97dfac18dd8911819))? Ptherwise I can provide a downloadable asset for you to try with.

**Comment by iglnierod** [comment] 2024-04-27 08:08
@TheCommieAxolotl I would appreciate if you provided me with a .deb file to try it out.

**Comment by TheCommieAxolotl** [comment] 2024-04-27 08:21
Sure, here's a .deb I built with my local copy, let me know if it doesn't work 
https://file.io/3Nw2k6ontB4L

**Comment by iglnierod** [comment] 2024-04-27 08:41
When depackagin I'm getting this error:
![image](https://github.com/relagit/relagit/assets/115586378/e639e336-b2d2-4895-9afa-05503a3deaaf)
```txt
dpkg: error processing archive RelaGit-linux.deb (--install):
 package architecture (arm64) does not match system (amd64)
Errors were encountered while processing:
 RelaGit-linux.deb
 ```

**Comment by TheCommieAxolotl** [comment] 2024-04-27 09:01
Ah, I'm on an arm64 MacBook so that's probably expected. From my testing the commit seems to have fixed the corruption error so I'll close this as completed for now.

If when 0.14.9 rolls around and this isn't fixed please feel free to mention me in a comment here and I'll reopen.

Thanks for the issue!

**Closed by TheCommieAxolotl** 2024-04-27 09:01 UTC
Labels: bug, triage
